name: Testing CI pipeline

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@1ff5a18cc396177ebd27c4250f7132e72af93462
      - name: Run chmod to make gradlew executable
        run: chmod +x gradlew

      - name: Execute tests
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: cleanTest test jacocoTestReport sonar



